name: Update Gist

on:
  push:
    branch: master

  schedule:
    - cron: "0 0 * * *"

jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Update gist
        run: node ./dist/index.js
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 97b738c515448231e85fc48014be5b3b
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
